#                                                                        #
# Routes configuration for the GermaniaSacra package                     #
#                                                                        #

-
  name: 'Kloster List URI'
  uriPattern: ''
  defaults:
    '@controller': 'Kloster'
    '@action': 'list'

-
  name: 'Proxy for static files'
  uriPattern: 'entity/{entityName}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
    '@controller': 'Proxy'
    '@action':     'entity'
    '@format': 'json'

-
  name: 'Search Ort'
  uriPattern: 'searchOrt'
  defaults:
    '@controller': 'Kloster'
    '@action': 'searchOrt'

-
  name: 'Search'
  uriPattern: 'search'
  defaults:
    '@controller': 'Kloster'
    '@action': 'search'

-
  name: 'data import'
  uriPattern: 'importdump'
  defaults:
    '@controller': 'DataImport'
    '@action': 'importdump'

-
  name: 'incremental data import'
  uriPattern: 'importinkdump'
  defaults:
    '@controller': 'dataimport'
    '@action': 'importinkdump'

-
  name: 'publish'
  uriPattern: 'publish'
  defaults:
    '@controller': 'DataExport'
    '@action': 'mysql2solrExport'

-
  name: 'create mysql database dump'
  uriPattern: 'dump'
  defaults:
    '@controller': 'Dump'
    '@action':     'dump'

-
  name: 'importlog'
  uriPattern: 'importlog'
  defaults:
    '@controller': 'DataImport'
    '@action': 'log'

-
  name: 'Get select options'
  uriPattern: 'getOptions'
  defaults:
    '@controller': 'Kloster'
    '@action': 'getOptions'

-
  name: 'Default list routes (controller only)'
  uriPattern: '{@controller}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
    '@action':     'list'

-
  name: 'Default list routes (controller with action)'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
    '@format': 'json'

-
  name: 'Default list routes (controller with action and id)'
  uriPattern: '{@controller}/{@action}/{uUID}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
