#                                                                        #
# Routes configuration for the GermaniaSacra package                     #
#                                                                        #

-
  name: 'Kloster List URI'
  uriPattern: ''
  defaults:
    '@controller': 'Kloster'
    #'@action': 'index'

-
  name: 'JSON-List Kloster URI'
  uriPattern: 'jsonList'
  defaults:
    '@controller': 'Kloster'
    '@action': 'jsonList'

-
  name: 'JSON-List-All Kloster URI'
  uriPattern: 'klosterListAll'
  defaults:
    '@controller': 'Kloster'
    '@action': 'klosterListAll'

-
  name: 'Proxy for static files'
  uriPattern: 'entity/{entityName}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
    '@controller': 'Proxy'
    '@action':     'entity'
    '@format': 'json'

-
  name: 'Search Ort'
  uriPattern: 'searchOrt'
  defaults:
    '@controller': 'Kloster'
    '@action': 'searchOrt'

-
  name: 'Search'
  uriPattern: 'search'
  defaults:
    '@controller': 'Kloster'
    '@action': 'search'

-
  name: 'Get select options'
  uriPattern: 'getOptions'
  defaults:
    '@controller': 'Kloster'
    '@action': 'getOptions'

-
  name: 'Update Solr after list update URI'
  uriPattern: 'updateSolrAfterListUpdate'
  defaults:
    '@controller': 'Kloster'
    '@action': 'updateSolrAfterListUpdate'

-
  name: 'Update Solr after kloster update URI'
  uriPattern: 'updateSolrAfterKlosterUpdate'
  defaults:
    '@controller': 'Kloster'
    '@action': 'updateSolrAfterKlosterUpdate'

-
  name: 'Update Solr after kloster create URI'
  uriPattern: 'solrUpdateWhenKlosterCreate'
  defaults:
    '@controller': 'Kloster'
    '@action': 'solrUpdateWhenKlosterCreate'

-
  name: 'Default list routes (controller only)'
  uriPattern: '{@controller}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
    '@action':     'list'

-
  name: 'Default list routes (controller with action)'
  uriPattern: '{@controller}/{@action}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'

-
  name: 'Default list routes (controller with action and id)'
  uriPattern: '{@controller}/{@action}/{uuid}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'