#                                                                        #
# Routes configuration for the GermaniaSacra package                     #
#                                                                        #
-
  name: 'Kloster List URI'
  uriPattern: ''
  defaults:
    '@controller': 'Kloster'
    '@action': 'index'
-
  name: 'JSON-List Kloster URI'
  uriPattern: 'jsonList'
  defaults:
    '@controller': 'Kloster'
    '@action': 'jsonList'

-
  name: 'JSON-List-All Kloster URI'
  uriPattern: 'klosterListAll'
  defaults:
    '@controller': 'Kloster'
    '@action': 'klosterListAll'

-
  name: 'Update_List Kloster URI'
  uriPattern: 'updateList'
  defaults:
    '@controller': 'Kloster'
    '@action': 'updateList'

-
  name: 'Proxy for static files'
  uriPattern: 'entity/{entityName}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
    '@controller': 'Proxy'
    '@action':     'entity'
    '@format': 'json'

-
  name: 'Search Ort'
  uriPattern: 'searchOrt'
  defaults:
    '@controller': 'Kloster'
    '@action': 'searchOrt'

-
  name: 'Search'
  uriPattern: 'search'
  defaults:
    '@controller': 'Kloster'
    '@action': 'search'

-
  name: 'Edit Kloster URI'
  uriPattern: 'edit/{kloster.__identity}'
  defaults:
    '@controller': 'Kloster'
    '@action': 'edit'

-
  name: 'Get Kloster Options URI'
  uriPattern: 'getOptions'
  defaults:
    '@controller': 'Kloster'
    '@action': 'getOptions'

-
  name: 'Update Kloster URI'
  uriPattern: 'update/{kloster.__identity}'
  defaults:
    '@controller': 'Kloster'
    '@action': 'update'
    '@format': 'json'

-
  name: 'Update Kloster URI'
  uriPattern: 'delete/{kloster.__identity}'
  defaults:
    '@controller': 'Kloster'
    '@action': 'delete'

-
  name: 'New Kloster URI'
  uriPattern: 'new'
  defaults:
    '@controller': 'Kloster'
    '@action': 'new'

-
  name: 'Create Kloster URI'
  uriPattern: 'create'
  defaults:
    '@controller': 'Kloster'
    '@action': 'create'

-
  name: 'Add Kloster Id URI'
  uriPattern: 'addKlosterId'
  defaults:
    '@controller': 'Kloster'
    '@action': 'addKlosterId'

-
  name: 'Update Solr after list update URI'
  uriPattern: 'updateSolrAfterListUpdate'
  defaults:
    '@controller': 'Kloster'
    '@action': 'updateSolrAfterListUpdate'

-
  name: 'Update Solr after kloster update URI'
  uriPattern: 'updateSolrAfterKlosterUpdate'
  defaults:
    '@controller': 'Kloster'
    '@action': 'updateSolrAfterKlosterUpdate'

-
  name: 'Update Solr after kloster create URI'
  uriPattern: 'solrUpdateWhenKlosterCreate'
  defaults:
    '@controller': 'Kloster'
    '@action': 'solrUpdateWhenKlosterCreate'

-
  name: 'New Ort URI'
  uriPattern: 'ort/new'
  defaults:
    package: 'Subugoe.GermaniaSacra'
    '@controller': 'Ort'
    '@action': 'new'
    '@format': 'html'

-
  name: 'Default list routes'
  uriPattern: '{@controller}'
  defaults:
    '@package': 'Subugoe.GermaniaSacra'
    '@action':     'list'