#                                                                        #
# Default routes configuration for the Welcome package                   #
#                                                                        #
-
  name: 'kloster List URI'
  uriPattern: 'kloster'
  defaults:
    '@package':    'SUB.Germania'
    '@controller': 'Kloster'

-
#  name: 'Kloster List URI'
#  uriPattern: 'klosters'
#  defaults:
#    '@package': 'SUB.Germania'
#    '@controller': 'Kloster'
#    '@action': 'index'
#    '@format': 'json'

#-
#  name: 'Edit Klosterstandort URI'
#  uriPattern: 'klosterstandort/{@action}/{klosterstandort.__identity}'
#  defaults:
#    '@package':    'SUB.Germania'
#    '@controller': 'Klosterstandort'
#    '@action': 'edit'