Subugoe:
  GermaniaSacra:
    data:
      geoJson: 'http://adw-goe.de/typo3conf/ext/tmpl_adw/Resources/Public/Images/GermaniaSacra/Bistumsgrenzen/GSBistumsgrenzenGEOJSON.geojson'
      literature: 'http://adw-goe.de/api/forschung/forschungsprojekte-akademienprogramm/germania-sacra/klosterdatenbank/bibliographieinterface/bibliography/588/'
TYPO3:
  Flow:
    object:
      excludeClasses:
        'solarium.*': ['.*']
        'knplabs.*': ['.*']
  Jobqueue:
    Common:
      queues:
        'kloster':
          className: 'Subugoe\Jobqueue\Redis\Queue\RedisQueue'