Subugoe:
  GermaniaSacra:
    mysql:
      server: '127.0.0.1'
      port: 3306
      user: 'root'
      password: 'vagrant'
      database: 'germania'
    data:
      geoJson: 'http://adw-goe.de/typo3conf/ext/tmpl_adw/Resources/Public/Images/GermaniaSacra/Bistumsgrenzen/GSBistumsgrenzenGEOJSON.geojson'
      literature: 'http://dev.adw-goe.de/api/germania-sacra/klosterdatenbank/rest/bibliography/520/'
TYPO3:
  Flow:
    object:
      excludeClasses:
        'solarium.*': ['.*']
        'knplabs.*': ['.*']